Add batch file launching NS for playing vanilla
R2Northstar/Northstar pull request #319
Opened 2022-08-06 23:52 UTC by GeckoEidechse

Using a separate profile to ensure no mods loaded and enabling ClientCommands should allow playing on vanilla servers.

Note that using Northstar on vanilla servers breaks sending/receiving Origin invites for the player using Northstar. They can however still join others via Origin just fine.

2022-10-15 16:58 UTC, F1F7Y approved these changes
Works as expected

2022-11-03 22:51 UTC, ASpoonPlaysGames commented
Does/should this automatically create the R2Vanilla directory, for logging etc.?

2022-11-03 22:52 UTC, uniboi commented
Yes.

2022-11-03 23:00 UTC, ASpoonPlaysGames requested changes

2022-11-03 23:00 UTC, ASpoonPlaysGames commented on release/r2vanilla.bat
> +NorthstarLauncher.exe -norestrictservercommands -profile=R2Vanilla
```suggestion
start "NorthstarLauncher | R2Vanilla" NorthstarLauncher.exe -norestrictservercommands -profile=R2Vanilla
```
Personally I would prefer if the bat file was to start northstar as a separate process, so that it would use the correct slot in the Taskbar, etc.
Using this you can also set the window title on launch, to indicate that Northstar is being launched in "vanilla"


Before suggested change:
![image](https://user-images.githubusercontent.com/66967891/199850938-7d9eb689-d095-438f-894e-d0b4a754694e.png)
![image](https://user-images.githubusercontent.com/66967891/199850929-d499f367-8244-4a5c-a519-f3dcf0a19da0.png)

After suggested change:
![image](https://user-images.githubusercontent.com/66967891/199851023-2636f4bf-d02f-46a7-bd9f-e84e11f7aa0a.png)
![image](https://user-images.githubusercontent.com/66967891/199851017-ff79aba9-0895-4d74-bd89-ca845f6e278f.png)

2023-07-04 15:02 UTC, F1F7Y commented
Would prefer #496 over this

2023-09-03 09:16 UTC, ASpoonPlaysGames commented
> Would prefer #496 over this

I agree, this PR is probably unnecessary at this point

2023-09-14 22:43 UTC, GeckoEidechse commented
Closing as no longer wanted.

2023-09-14 22:43 UTC, closed without merging